# Generated by Django 3.2.2 on 2021-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0002_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'cities'},
        ),
    ]
