# Generated by Django 3.1.5 on 2021-05-06 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0003_alter_city_options'),
        ('exercise_app', '0002_appuser_location'),
    ]

    operations = [
    ]
