# Generated by Django 3.1.5 on 2021-05-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0004_merge_20210506_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='owm_id',
            field=models.PositiveIntegerField(default=1, verbose_name='id'),
            preserve_default=False,
        ),
    ]
